### PR TITLE
fix: wrong import of TokenWhiteList prisma type

### PR DESCRIPTION
**Pull request by dhruvin-rv**
Wrong import was stopping server to start

### CODE REVIEW

**Comment by v-checha** [comment]
@dhruvin-rv  All Entities must me import from Prisma generated types, did you run migrations and generated types command?

**Comment by dhruvin-rv** [comment]
Yes i ran the prisma generate but the import which is mentioned from ./ is not right it should be from generated prisma types it self

**Comment by Vladyslav317** [comment]
@dhruvin-rv  I've just tried running the server on your branch, and it works without an alias. Are you sure you ran db:generate and db:push?

**Comment by dhruvin-rv** [comment]
Hi yes but then it could be some other issue never mind

**Comment by v-checha** [comment]
@dhruvin-rv Thanks, I am closing PR.

**Pull request closed without merging**
